### ISSUE TITLE
ERROR: Cannot Read Manifest

### ISSUE THREAD

**Issue by yevdam** [yevdam/pringles-bot#10]
Full error:
Exception has occurred: SessionNotCreatedException
Message: session not created: cannot process extension #1
from unknown error: cannot read manifest

**Comment by bestadamdagoat** [comment]
The reason you are getting this error is because you have an extra folder inside of the anticaptcha-blank.zip folder. You can fix this by selecting all the files inside your anticaptcha-blank folder and then zipping it. Make sure it isn't named anticaptcha-blank(1).zip or anything like that.
